[constellation]
name  = "ExampleConstellation"
epoch = 2025-05-20T00:00:00Z

[[constellation.shells]]
name = "LEO-500km-43deg"
count = 3
planes = 1
phasing = 1
apogee_altitude = 500
eccentricity = 0.0001
inclination = 43.0
raan_range = 360.0
# raan_start = 0.0
# argp = 0.0
# mean_anomaly_0 = 0.0
