[constellation]
name = "ExampleConstellation"
epoch = "2025-05-22T00:00:00Z"

[[constellation.shells]]
name = "LEO-550km-53deg"
count = 66
planes = 6
phasing = 2
apogee_altitude = 550
eccentricity = 0.0001
inclination = 53.0
raan_range = 360.0
# raan_start = 0.0
# argp = 0.0
# mean_anomaly_0 = 0.0
