[[groundstations]]
name = "Tokyo"
latitudeDeg = 35.6895
longitudeDeg = 139.6917
heightKm = 0
minElevationDeg = 40

[[groundstations]]
name = "Sydney"
latitudeDeg = -33.8688
longitudeDeg = 151.2093
heightKm = 0
minElevationDeg = 25
