// This file is auto-generated by scripts/generate-satellites.ts
// Do not edit manually.
import type { SatelliteSpec } from './satellites';
export const CUSTOM_SATELLITES: SatelliteSpec[] = [
  {
    "type": "elements",
    "elements": {
      "satnum": 90001,
      "epoch": "2025-05-20T00:00:00.000Z",
      "semiMajorAxisKm": 7000,
      "eccentricity": 0.001,
      "inclinationDeg": 40,
      "raanDeg": 0,
      "argPerigeeDeg": 0,
      "meanAnomalyDeg": 0
    }
  }
];
